#!/usr/bin/env python3
"""
Build a D1 seed file from the live MongoDB-backed API.

Data is pulled through the old Express API rather than MongoDB directly, so no
Atlas credentials are needed. Mongo `_id` values are reused verbatim as D1 ids,
which is what keeps SHELF_ID_CLOUD in the Jetson's .env valid after the switch.

Usage:
    python scripts/migrate-from-mongo.py [API_BASE] > migrations/seed.sql
    npx wrangler d1 execute smart-shelf --remote --file=migrations/seed.sql
    del migrations\seed.sql        # it contains a live SePay token

Passwords are NOT exported (the old API strips them), so migrated users get a
placeholder hash that cannot match. Create a fresh admin login on the new
backend with POST /api/users/register.
"""
import json
import sys
import urllib.request

API = (sys.argv[1] if len(sys.argv) > 1
       else "https://smart-shelf-server-backend.onrender.com/api")

# Nothing can bcrypt-compare true against this, so a migrated account cannot be
# logged into until its password is set deliberately.
PLACEHOLDER_PW = "!migrated-no-password"


def fetch(path):
    with urllib.request.urlopen(f"{API}/{path}", timeout=120) as r:
        d = json.load(r)
    if isinstance(d, dict):
        for k in ("data", "products", "users"):
            if k in d:
                return d[k]
        return [d]
    return d


def q(v):
    """SQL literal."""
    if v is None or v == "":
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def row(table, cols, vals):
    return (f"INSERT OR REPLACE INTO {table} ({', '.join(cols)}) "
            f"VALUES ({', '.join(q(v) for v in vals)});")


out = ["-- Generated by scripts/migrate-from-mongo.py"]
# D1 rejects BEGIN TRANSACTION/COMMIT - it wraps executed files itself.

# --- shelves -------------------------------------------------------------
shelves = fetch("shelves")
shelf_ids = {s["_id"] for s in shelves}
for s in shelves:
    out.append(row("shelves",
        ["id", "shelf_id", "shelf_name", "mac_ip", "location", "qr", "createdAt", "updatedAt"],
        [s["_id"], s.get("shelf_id"), s.get("shelf_name"), s.get("mac_ip"),
         s.get("location"), s.get("qr"), s.get("createdAt"), s.get("updatedAt")]))

# --- users ---------------------------------------------------------------
users = fetch("users")
user_ids = {u["_id"] for u in users}
for u in users:
    out.append(row("users",
        ["id", "username", "rfid", "email", "password", "fullName", "phone",
         "avatar", "address", "dateOfBirth", "gender", "role", "isActive",
         "emailVerified", "createdAt", "updatedAt"],
        [u["_id"], u.get("username"), u.get("rfid"), u.get("email"),
         PLACEHOLDER_PW, u.get("fullName"), u.get("phone"), u.get("avatar", ""),
         u.get("address"), u.get("dateOfBirth"), u.get("gender"),
         u.get("role", "employee"), u.get("isActive", True),
         u.get("emailVerified", False), u.get("createdAt"), u.get("updatedAt")]))

# shelf <-> user links come from the shelf's embedded user_id array
for s in shelves:
    for u in s.get("user_id") or []:
        uid = u["_id"] if isinstance(u, dict) else u
        if uid in user_ids:
            out.append(row("shelf_users", ["shelf_id", "user_id"], [s["_id"], uid]))

# --- products ------------------------------------------------------------
products = fetch("products")
product_ids = {p["_id"] for p in products}
for p in products:
    out.append(row("products",
        ["id", "product_id", "product_name", "img_url", "price", "discount",
         "stock", "weight", "max_quantity", "threshold", "createdAt", "updatedAt"],
        [p["_id"], p.get("product_id"), p.get("product_name"), p.get("img_url"),
         p.get("price", 0), p.get("discount", 0), p.get("stock", 0),
         p.get("weight", 0), p.get("max_quantity", 1), p.get("threshold", 1),
         p.get("createdAt"), p.get("updatedAt")]))

# --- loadcells -----------------------------------------------------------
# Half the rows belong to a shelf that no longer exists (deleted upstream);
# importing them would violate the shelf foreign key, so they are skipped.
skipped = 0
for c in fetch("loadcell"):
    sid = c.get("shelf_id")
    sid = sid["_id"] if isinstance(sid, dict) else sid
    if sid not in shelf_ids:
        skipped += 1
        continue
    pid = c.get("product_id")
    pid = pid["_id"] if isinstance(pid, dict) else pid
    prev = c.get("previous_product_id")
    prev = prev["_id"] if isinstance(prev, dict) else prev
    out.append(row("loadcells",
        ["id", "load_cell_id", "load_cell_name", "product_id",
         "previous_product_id", "shelf_id", "floor", "column_index",
         "threshold", "quantity", "error"],
        [c["_id"], c.get("load_cell_id", 0), c.get("load_cell_name"),
         pid if pid in product_ids else None,
         prev if prev in product_ids else None,
         sid, c.get("floor", 1), c.get("column", 1),
         c.get("threshold", 1), c.get("quantity", 0), c.get("error", 0)]))

# --- posters -------------------------------------------------------------
for p in fetch("posters"):
    out.append(row("posters", ["id", "image_url", "createdAt", "updatedAt"],
        [p["_id"], p.get("image_url"), p.get("createdAt"), p.get("updatedAt")]))

# --- combos --------------------------------------------------------------
for c in fetch("combos"):
    out.append(row("combos",
        ["id", "name", "description", "image", "price", "oldPrice",
         "validFrom", "validTo", "createdAt", "updatedAt"],
        [c["_id"], c.get("name"), c.get("description", ""), c.get("image", ""),
         c.get("price", 0), c.get("oldPrice", 0), c.get("validFrom"),
         c.get("validTo"), c.get("createdAt"), c.get("updatedAt")]))
    for p in c.get("products") or []:
        pid = p["_id"] if isinstance(p, dict) else p
        if pid in product_ids:
            out.append(row("combo_products", ["combo_id", "product_id"], [c["_id"], pid]))

# --- sepay config --------------------------------------------------------
# WARNING: the old API *does* return the live sepayAuthToken, so the generated
# seed.sql holds a real payment credential. It is gitignored - keep it out of
# version control and delete it once applied.
for s in shelves:
    try:
        cfg = fetch(f"sepay-config/shelf/{s['_id']}")[0]
    except Exception:
        continue
    if not cfg or cfg.get("error"):
        continue
    out.append(row("sepay_configs",
        ["id", "shelf_id", "vietqrAccountNo", "vietqrAccountName", "vietqrAcqId",
         "sepayAuthToken", "sepayBankAccountId", "merchantCode", "webhookUrl",
         "callbackUrl", "sandbox", "active", "createdAt", "updatedAt"],
        [cfg.get("_id"), s["_id"], cfg.get("vietqrAccountNo"),
         cfg.get("vietqrAccountName"), cfg.get("vietqrAcqId"),
         cfg.get("sepayAuthToken"), cfg.get("sepayBankAccountId"),
         cfg.get("merchantCode"), cfg.get("webhookUrl"), cfg.get("callbackUrl"),
         cfg.get("sandbox", True), cfg.get("active", True),
         cfg.get("createdAt"), cfg.get("updatedAt")]))

print("\n".join(out))
print(f"-- shelves={len(shelves)} users={len(users)} products={len(products)} "
      f"loadcells_skipped_orphan={skipped}", file=sys.stderr)
